-- SELECT * FROM NOMINA.PROVINCIA;
-- SELECT * FROM NOMINA.CANTON;
-- SET TABLE NOMINA.PROVINCIA SOURCE "./ETC/CSV/PROVINCIA.CSV"
-- SELECT * FROM NOMINA.FORMULA;

-- SELECT * FROM NOMINA.ROLPAGODETALLE;
SELECT * FROM NOMINA.preferencias;
